### ISSUE TITLE
Actions 入れる

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-manager#21]
# なんでやるの？
- CI/CD やりたいから
- Lint やテストがちゃんとパスしてるかを検知したい

# 受入条件
- [ ] #18 終わったあとに cloud functions に自動デプロイする GitHub Actions がいれられてること
- [ ] GAS に自動デプロイする GitHub Actions がいれられてること
- [ ] #20 終わったあとに Lint をチェックする GitHub Actions がいれられてること
- [ ] #22 終わったあとに テストを走らす GitHub Actions がいれられてること

# 備考
スコープでかいんで、あれだったらバラしてください（各チェックリストごとに子イシューにするとか）
ただイメージとしてはあったがええなLv.なんで
#22 まで全部終わったら着手したいって感じ
できるとこは各イシューのステップごとにタイミングはあるのでそん時にチャレンジしてもよし
今なら　GAS は出来そう。。。
